#!/usr/bin/env python3
"""Carola OCV — the two mask layers from the committed window-payload cache.

Carola Bruecke (Dresden) is observed as one **per-girder** record: the export
stores, per acquisition, one 80x80 complex chip per girder request (segment
0/1/2 -> Girder A/B/C) and, for the wrongly typed tower asset, 7x7 chips. This
module owns the two mask layers of the package:

  * the **echo mask** — the project-wide bridge-deck echo definition, identical
    to ``analyze_carola_coherence.coherence_gamma2`` and to the backend's
    ``sarsolve::coherence::coherence_mast_echo``:

        intensity = |z|^2
        peak      = max(intensity)
        median    = np.median(intensity)           <- mean of the two central
                                                      values (the *LUMO*
                                                      convention; the KDLO
                                                      upper median is another
                                                      site)
        mask      = intensity >= 0.30 * peak  and  intensity >= 5.0 * median
        A         = count(mask)                    (no echo if A < 2)
        gamma2    = |sum(z[mask])|^2 / (A * sum(|z[mask]|^2)),  clamped to [0, 1]

  * the **per-girder deck mask** — the very same rule applied to the chip that
    the *girder's own* decode point produced (``segment_index`` of the export
    index, labelled by ``carola_segments.txt``). Same six dimensions, but only
    the pixels of that girder's deck window.

Why a committed cache and not the raw payloads
----------------------------------------------
The committed windows file is 182 MB (2,454 lines x 80x80 complex, JSON) — far
beyond what belongs in this repository. The cache
``data/carola/carola_windows_mask_cache.txt`` is therefore the mask layer's
committed input, the Carola analogue of the KDLO strip cache: the *echo mask of
every chip* (pixel coordinates) plus the sufficient statistics the six
dimensions need

    peak, median, max_masked, min_masked, ss_re, ss_im, ss_abs2, n_masked, px

so that everything below is recomputed here and nothing is read from a stored
result:

  * ``A = n_masked``, ``D = A / bbox_area``, ``F`` = 8-connected components,
    ``S = ||centroid - peak||`` are derived from the committed ``px`` set;
  * ``gamma2 = (ss_re^2 + ss_im^2) / (A * ss_abs2)`` is recomputed exactly (the
    sums are stored at full double precision);
  * the **mask rule is re-verified on the committed mask**: every masked pixel
    must satisfy ``|z|^2 >= 0.30*peak`` and ``>= 5.0*median``, the brightest
    masked pixel must *be* the peak (``max_masked == peak``), and ``A >= 2``.
    A chip whose committed mask violates the rule is refused;
  * ``P`` — the mask persistence — is recomputed from the committed masks of
    all chips of the majority shape (see ``add_persistence``).

The cache is written once by ``--extract`` (a one-time offline step that needs
the 182 MB file, exactly as ``kdlo_ocv_channels_csv.py --fetch-db-extra`` needs
the database), records the source file's sha256 in its manifest, and is
thereafter the only mask input of the build.

Derivation
----------
  A = n_masked                       (echo pixels, ``coherence_masked_pixels``)
  D = A / bbox_area                  (bounding-box fill of the echo)
  F = number of 8-neighbourhood components
  S = ||mask centroid - peak pixel|| in px
  P = mean pixel frequency inside the own mask (over all chips of the shape)

Usage
-----
  python3 code/carola/carola_ocv_masks.py --extract   # once, needs the 182 MB file
  python3 code/carola/carola_ocv_masks.py --check     # acceptance test, no payload
"""
from __future__ import annotations

import argparse
import hashlib
import json
import os
import sys
from collections import Counter, defaultdict

import numpy as np

HERE = os.path.dirname(os.path.abspath(__file__))
DATA = os.path.join(HERE, os.pardir, os.pardir, "data", "carola")

CACHE_PATH = os.path.join(DATA, "carola_windows_mask_cache.txt")
MANIFEST_PATH = os.path.join(DATA, "carola_windows_mask_cache.manifest.json")
MEAS_PATH = os.path.join(DATA, "carola_measurements_full.txt")
INDEX_PATH = os.path.join(DATA, "carola_windows_index.txt")
SEGMENTS_PATH = os.path.join(DATA, "carola_segments.txt")

# The one committed source that does not fit into the repository. ``--extract``
# reads it from the analysis project (or from ``--windows``); its sha256 travels
# in the manifest so the cache can be regenerated byte-for-byte.
DEFAULT_WINDOWS = "/home/projects/carola_analysis/carola_windows_full.txt"

PEAK_FRAC = 0.30
MEDIAN_MULT = 5.0
MIN_N_MASKED = 2
WINDOW_SIZE = 80
RULE_TOL = 1e-9

CACHE_COLUMNS = ["mid", "asset", "segment", "date", "orbit", "w", "h",
                 "peak", "median", "max_masked", "min_masked",
                 "ss_re", "ss_im", "ss_abs2", "n_masked",
                 "peak_row", "peak_col", "n_components", "largest_component", "px"]

# The mask dimensions the cache carries (gamma2 is derived, not stored).
MASK_COLUMNS = ["A", "D", "F", "S", "P", "gamma2"]


# ---------------------------------------------------------------------------
# The echo mask itself (port of analyze_carola_coherence.coherence_gamma2 and
# carola_segment_c_mask_gate.mask_metrics / largest_component)
# ---------------------------------------------------------------------------
def largest_component(mask):
    """``(n_components, largest_size)`` of a 2-D boolean mask, 8-connectivity.

    Dependency-free BFS, verbatim from
    ``carola_segment_c_mask_gate.largest_component``.
    """
    h, w = mask.shape
    seen = np.zeros_like(mask, dtype=bool)
    sizes = []
    for r0 in range(h):
        for c0 in range(w):
            if not mask[r0, c0] or seen[r0, c0]:
                continue
            stack = [(r0, c0)]
            seen[r0, c0] = True
            size = 0
            while stack:
                r, c = stack.pop()
                size += 1
                for dr in (-1, 0, 1):
                    for dc in (-1, 0, 1):
                        rr, cc = r + dr, c + dc
                        if (0 <= rr < h and 0 <= cc < w and mask[rr, cc]
                                and not seen[rr, cc]):
                            seen[rr, cc] = True
                            stack.append((rr, cc))
            sizes.append(size)
    return len(sizes), (max(sizes) if sizes else 0)


def echo_mask(z, peak_frac=PEAK_FRAC, median_mult=MEDIAN_MULT,
              min_n_masked=MIN_N_MASKED):
    """The project-wide bridge-deck echo mask of one complex window.

    ``z`` is the ``(h, w)`` complex chip. Returns ``None`` when the window has
    no echo (``peak <= 0`` or fewer than ``min_n_masked`` masked pixels), else a
    dict with the mask and the sufficient statistics of the six dimensions.
    """
    intensity = np.abs(z) ** 2
    peak = float(intensity.max())
    if peak <= 0.0:
        return None
    median = float(np.median(intensity))
    mask = (intensity >= peak_frac * peak) & (intensity >= median_mult * median)
    n_masked = int(mask.sum())
    if n_masked < min_n_masked:
        return None
    rows, cols = np.nonzero(mask)
    sel = z[mask]
    masked_int = intensity[mask]
    peak_row, peak_col = np.unravel_index(int(np.argmax(intensity)), intensity.shape)
    n_comp, largest = largest_component(mask)
    return {
        "mask": mask,
        "shape": (int(z.shape[0]), int(z.shape[1])),
        "A": n_masked,
        "peak": peak,
        "median": median,
        "max_masked": float(masked_int.max()),
        "min_masked": float(masked_int.min()),
        "ss_re": float(sel.real.sum()),
        "ss_im": float(sel.imag.sum()),
        "ss_abs2": float((sel.real ** 2 + sel.imag ** 2).sum()),
        "peak_row": int(peak_row),
        "peak_col": int(peak_col),
        "px": sorted((int(r), int(c)) for r, c in zip(rows, cols)),
        "n_components": n_comp,
        "largest_component": largest,
    }


def gamma2_of(ss_re, ss_im, ss_abs2, n_masked):
    """``|sum z|^2 / (A * sum |z|^2)`` from the committed sums (clamped)."""
    den = float(n_masked) * float(ss_abs2)
    if den <= 0.0:
        return None
    return float(min(max((ss_re * ss_re + ss_im * ss_im) / den, 0.0), 1.0))


def vector_from_row(row):
    """The 6D echo-mask vector of one cache row (mask rule re-verified)."""
    px = row["px"]
    A = len(px)
    if A != row["n_masked"]:
        raise ValueError(f"{row['mid']}: n_masked {row['n_masked']} != |px| {A}")
    if A < MIN_N_MASKED:
        raise ValueError(f"{row['mid']}: A={A} < {MIN_N_MASKED}")
    peak, median = row["peak"], row["median"]
    lo_thr = max(PEAK_FRAC * peak, MEDIAN_MULT * median)
    if row["min_masked"] * (1.0 + RULE_TOL) < lo_thr:
        raise ValueError(f"{row['mid']}: committed mask violates the rule "
                         f"(min|z|^2={row['min_masked']!r} < {lo_thr!r})")
    if abs(row["max_masked"] - peak) > RULE_TOL * max(peak, 1e-30):
        raise ValueError(f"{row['mid']}: peak {peak!r} is not a masked pixel "
                         f"(max_masked={row['max_masked']!r})")
    rows = np.array([r for r, _ in px], dtype=float)
    cols = np.array([c for _, c in px], dtype=float)
    row_span = int(rows.max() - rows.min() + 1)
    col_span = int(cols.max() - cols.min() + 1)
    bbox_area = int(row_span * col_span)
    cen_r, cen_c = float(rows.mean()), float(cols.mean())
    return {
        "A": A,
        "D": (A / bbox_area) if bbox_area > 0 else None,
        "F": row["n_components"],
        "S": float(np.hypot(cen_r - row["peak_row"], cen_c - row["peak_col"])),
        "gamma2": gamma2_of(row["ss_re"], row["ss_im"], row["ss_abs2"], A),
        "bbox_area": bbox_area,
        "row_span": row_span,
        "col_span": col_span,
        "centroid_row": cen_r,
        "centroid_col": cen_c,
        "peak_row": row["peak_row"],
        "peak_col": row["peak_col"],
        "n_components": row["n_components"],
        "largest_component": row["largest_component"],
        "fragmentation": (1.0 - row["largest_component"] / float(max(A, 1))),
    }


def add_persistence(rows):
    """``P`` = mean pixel frequency inside the own mask.

    A pixel-exact frequency map is only comparable across dates with the same
    chip shape; chips of a different shape get ``P = None`` instead of being
    silently misaligned. Every Carola bridge chip is 80x80, so the majority
    shape is the whole record (the 7x7 tower chips never enter the cache).
    """
    if not rows:
        return {"majority_shape": None, "n_majority_shape": 0,
                "n_excluded_other_shape": 0}
    shape_counts = Counter(tuple(r["shape"]) for r in rows)
    majority_shape, n_majority = shape_counts.most_common(1)[0]
    freq = np.zeros(majority_shape, dtype=float)
    n_used = 0
    for r in rows:
        if tuple(r["shape"]) == majority_shape:
            freq[r["mask_rows"], r["mask_cols"]] += 1.0
            n_used += 1
    freq /= max(n_used, 1)
    n_excluded = 0
    for r in rows:
        if tuple(r["shape"]) != majority_shape:
            r["P"] = None
            n_excluded += 1
            continue
        v = freq[r["mask_rows"], r["mask_cols"]]
        r["P"] = float(v.mean())
        r["P_frac_ge_50pct"] = float((v >= 0.5).mean())
        r["P_frac_ge_30pct"] = float((v >= 0.3).mean())
    return {"majority_shape": list(majority_shape), "n_majority_shape": n_majority,
            "n_excluded_other_shape": n_excluded}


# ---------------------------------------------------------------------------
# Cache I/O
# ---------------------------------------------------------------------------
def _px_decode(text):
    if not text:
        return []
    out = []
    for p in text.split(";"):
        a, b = p.split(",")
        out.append((int(a), int(b)))
    return out


def _px_encode(px):
    return ";".join(f"{r},{c}" for r, c in px)


def load_cache(path=CACHE_PATH):
    """The committed mask cache as rows (mask as ``mask_rows`` / ``mask_cols``)."""
    rows = []
    with open(path) as fh:
        header = None
        for line in fh:
            if line.startswith("#"):
                continue
            parts = line.rstrip("\n").split("|")
            if header is None:
                header = parts
                continue
            d = dict(zip(header, parts))
            px = _px_decode(d.get("px", ""))
            d["w"], d["h"] = int(d["w"]), int(d["h"])
            d["n_masked"] = int(d["n_masked"])
            for k in ("peak", "median", "max_masked", "min_masked",
                      "ss_re", "ss_im", "ss_abs2"):
                v = d.get(k)
                d[k] = float(v) if v not in ("", None) else None
            pr, pc = d.get("peak_row"), d.get("peak_col")
            d["peak_row"] = int(pr) if pr not in ("", None) else None
            d["peak_col"] = int(pc) if pc not in ("", None) else None
            ncomp = d.get("n_components")
            d["n_components"] = int(ncomp) if ncomp not in ("", None) else None
            largest = d.get("largest_component")
            d["largest_component"] = int(largest) if largest not in ("", None) else None
            d["px"] = px
            d["shape"] = (d["h"], d["w"])
            d["mask_rows"] = np.array([r for r, _ in px], dtype=int)
            d["mask_cols"] = np.array([c for _, c in px], dtype=int)
            rows.append(d)
    return rows


def load_manifest(path=MANIFEST_PATH):
    with open(path) as fh:
        return json.load(fh)


def _sha256(path):
    h = hashlib.sha256()
    with open(path, "rb") as fh:
        for chunk in iter(lambda: fh.read(1 << 22), b""):
            h.update(chunk)
    return h.hexdigest()


# ---------------------------------------------------------------------------
# Extraction (one-time) — reads the 182 MB windows file
# ---------------------------------------------------------------------------
def _load_segments(path):
    """``(asset_id, segment_index) -> label`` (and the index-only fallback)."""
    labels, by_index = {}, {}
    if not path or not os.path.isfile(path):
        return labels, by_index
    with open(path) as fh:
        lines = fh.read().splitlines()
    if not lines or not lines[0].startswith("asset_id"):
        return labels, by_index
    for line in lines[1:]:
        p = line.split("|")
        if len(p) < 4:
            continue
        try:
            sidx = int(p[2])
        except ValueError:
            continue
        labels[(p[0], sidx)] = p[3]
        by_index.setdefault(sidx, p[3])
    return labels, by_index


def _load_index(path):
    idx = {}
    if not path or not os.path.isfile(path):
        return idx
    with open(path) as fh:
        for line in fh:
            p = line.rstrip("\n").split("|")
            if len(p) < 5:
                continue
            idx[p[0]] = {"asset": p[1], "asset_name": p[2], "segment_index": p[3],
                         "ts": p[4], "burst_id": p[5] if len(p) > 5 else ""}
    return idx


def extract(windows_path=DEFAULT_WINDOWS, out_path=CACHE_PATH,
            manifest_path=MANIFEST_PATH, size=WINDOW_SIZE):
    """Recompute the echo mask of every chip and write the committed cache.

    Replicates ``analyze_carola_coherence.load_data`` exactly: the join of the
    export index (``asset_name``/``segment_index``/``ts``), the payload
    deduplication on ``(asset, date, md5(payload)[:12])`` with first-occurrence
    wins, the segment resolution against ``carola_segments.txt`` and the window
    size filter. The guard counts are written into the manifest.
    """
    labels, by_index = _load_segments(SEGMENTS_PATH)
    index = _load_index(INDEX_PATH)
    rows, sizes, n_dup, n_no_echo, n_no_index = [], defaultdict(int), 0, 0, 0
    seen, groups = set(), defaultdict(lambda: defaultdict(set))
    with open(windows_path) as fh:
        for line in fh:
            parts = line.rstrip("\n").split("|", 3)
            if len(parts) < 4:
                continue
            mid, w, h, payload = parts[0], int(parts[1]), int(parts[2]), parts[3]
            im = index.get(mid)
            if im is None:
                n_no_index += 1
                continue
            ts = im.get("ts") or ""
            asset = im.get("asset_name") or ""
            h12 = hashlib.md5(payload.encode("utf-8")).hexdigest()[:12]
            seg_raw = im.get("segment_index")
            try:
                sidx = int(seg_raw) if seg_raw not in ("", None) else None
            except (TypeError, ValueError):
                sidx = None
            asset_id = im.get("asset")
            lbl = labels.get((asset_id, sidx)) if (asset_id and sidx is not None) else None
            segment = (lbl or (by_index.get(sidx) if sidx is not None else None)
                       or asset or (str(sidx) if sidx is not None else "?"))
            groups[(asset, ts[:10], im.get("burst_id") or ts)][
                str(sidx) if sidx is not None else "?"].add(h12)
            dedup_key = (asset, ts[:10], h12)
            if dedup_key in seen:
                n_dup += 1
                continue
            seen.add(dedup_key)
            if size and not (w == h == size):
                sizes[f"{w}x{h} (excluded)"] += 1
                continue
            sizes[f"{w}x{h}"] += 1
            arr = json.loads(payload)
            z = np.asarray([complex(a[0], a[1]) for a in arr]).reshape(h, w)
            m = echo_mask(z)
            if m is None:
                n_no_echo += 1
                continue
            rows.append({
                "mid": mid, "asset": asset, "segment": segment,
                "date": ts[:10], "orbit": "", "w": w, "h": h,
                "peak": m["peak"], "median": m["median"],
                "max_masked": m["max_masked"], "min_masked": m["min_masked"],
                "ss_re": m["ss_re"], "ss_im": m["ss_im"], "ss_abs2": m["ss_abs2"],
                "n_masked": m["A"], "px": m["px"],
                "peak_row": m["peak_row"], "peak_col": m["peak_col"],
                "n_components": m["n_components"],
                "largest_component": m["largest_component"],
                "shape": m["shape"],
                "mask_rows": np.array([r for r, _ in m["px"]], dtype=int),
                "mask_cols": np.array([c for _, c in m["px"]], dtype=int),
            })

    rows.sort(key=lambda r: (r["date"], r["asset"], r["segment"], r["mid"]))
    with open(out_path, "w") as fh:
        fh.write("# carola windows mask cache v1 — the echo mask of every committed "
                 "80x80 chip\n")
        fh.write(f"# rule: intensity >= {PEAK_FRAC} * max(intensity) AND "
                 f"intensity >= {MEDIAN_MULT} * np.median(intensity); "
                 f"min_n_masked={MIN_N_MASKED}\n")
        fh.write("# dedup: (asset_name, date, md5(payload)[:12]), first occurrence wins\n")
        fh.write("# extractor: code/carola/carola_ocv_masks.py --extract\n")
        fh.write("|".join(CACHE_COLUMNS) + "\n")
        for r in rows:
            fh.write("|".join([
                r["mid"], r["asset"], r["segment"], r["date"], r["orbit"],
                str(r["w"]), str(r["h"]),
                repr(r["peak"]), repr(r["median"]), repr(r["max_masked"]),
                repr(r["min_masked"]), repr(r["ss_re"]), repr(r["ss_im"]),
                repr(r["ss_abs2"]), str(r["n_masked"]),
                str(r["peak_row"]), str(r["peak_col"]), str(r["n_components"]),
                str(r["largest_component"]), _px_encode(r["px"]),
            ]) + "\n")

    multi = sum(1 for g in groups.values() if len(g) > 1)
    resolved = sum(1 for g in groups.values()
                   if len(g) > 1 and len(set().union(*g.values())) > 1)
    manifest = {
        "generator": "code/carola/carola_ocv_masks.py --extract",
        "out_cache": os.path.basename(out_path),
        "source_windows": os.path.abspath(windows_path),
        "source_windows_sha256": _sha256(windows_path),
        "source_index": os.path.basename(INDEX_PATH),
        "source_segments": os.path.basename(SEGMENTS_PATH),
        "mask_rule": {"peak_frac": PEAK_FRAC, "median_mult": MEDIAN_MULT,
                      "median_kind": "np.median", "min_n_masked": MIN_N_MASKED},
        "window_size": size,
        "n_rows": len(rows),
        "n_deduplicated_same_payload": n_dup,
        "n_without_index": n_no_index,
        "n_without_echo": n_no_echo,
        "window_sizes": dict(sizes),
        "asset_date_groups_with_several_segments": multi,
        "asset_date_groups_with_differing_payloads": resolved,
        "segment_resolved": bool(resolved),
    }
    with open(manifest_path, "w") as fh:
        json.dump(manifest, fh, indent=1, sort_keys=True)
    print(f"written: {os.path.relpath(out_path, DATA)} ({len(rows)} rows)")
    print(json.dumps({k: v for k, v in manifest.items()
                      if k != "source_windows"}, indent=1, sort_keys=True))
    return rows, manifest


# ---------------------------------------------------------------------------
# Acceptance test
# ---------------------------------------------------------------------------
def check(rows, manifest=None):
    """Re-verify the mask rule and the derived geometry of every cache row."""
    problems = []
    for r in rows:
        try:
            vector_from_row(r)
        except ValueError as exc:
            problems.append(str(exc))
        if tuple(r["shape"]) != (WINDOW_SIZE, WINDOW_SIZE):
            problems.append(f"{r['mid']}: shape {r['shape']} != "
                            f"({WINDOW_SIZE}, {WINDOW_SIZE})")
        if len(set(r["px"])) != len(r["px"]):
            problems.append(f"{r['mid']}: duplicate mask pixels")
    shapes = Counter(f"{h}x{w}" for (h, w) in (r["shape"] for r in rows))
    return {"n_checked": len(rows), "shapes": dict(shapes),
            "problems": problems[:40], "n_problems": len(problems)}


def main():
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--extract", action="store_true",
                    help="recompute the cache from the 182 MB windows file")
    ap.add_argument("--windows", default=DEFAULT_WINDOWS)
    ap.add_argument("--out", default=CACHE_PATH)
    ap.add_argument("--manifest", default=MANIFEST_PATH)
    ap.add_argument("--check", action="store_true",
                    help="acceptance test of the committed cache")
    ap.add_argument("--json", action="store_true", help="print the derived 6D vectors")
    args = ap.parse_args()

    if args.extract:
        extract(args.windows, args.out, args.manifest)

    rows = load_cache(args.out)
    rep = check(rows, load_manifest(args.manifest))
    if args.json:
        out = []
        for r in rows:
            v = vector_from_row(r)
            v["mid"] = r["mid"]
            v["segment"] = r["segment"]
            v["date"] = r["date"]
            out.append(v)
        print(json.dumps(out, indent=1, sort_keys=True))
    print(json.dumps({k: v for k, v in rep.items() if k != "problems"},
                     indent=1, sort_keys=True))
    if rep["problems"]:
        for p in rep["problems"][:40]:
            print("PROBLEM:", p)
        raise SystemExit(f"VERIFICATION FAILED ({rep['n_problems']} problems)")
    print("VERIFICATION OK")
    return 0


if __name__ == "__main__":
    sys.exit(main())
